### ISSUE TITLE
bug: Array declaration not parsable

### ISSUE THREAD

**Issue by l0nax** [alecthomas/participle#150]
We want to parse the following statements:
* `array[]`
* `array[5]`
* `array[5..]`
* `array[5..5]`
* `array[..5]`

The following code demonstrates the sub-set, where `participle` behaves not like we've defined the grammar:
```go
package main

import (
	"fmt"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
	"github.com/alecthomas/participle/v2/lexer/stateful"
	"github.com/l0nax/go-spew/spew"
)

type ArrayType struct {
	Pos lexer.Position

	Min     *int64 `@Int?`
	IsRange *bool  `( @".."? )?`
	Max     *int64 `( @Int? )?`
}

type Field struct {
	Pos lexer.Position

	IsArray bool       `( @"array" `
	Array   *ArrayType ` "[" @@? "]" )`
}

var basicLexer = stateful.MustSimple([]stateful.Rule{
	// {"Comment", `//.*|/\*.*?\*/`, nil},
	{"Int", `\d+`, nil},
	// {"Number", `(\d*\.)?\d+`, nil},
	// OR: 		{"Ident", `[a-zA-Z]\w*`, nil},
	// {"Ident", `\w+`, nil},
	// {"String", `"[^"]*"`, nil},
	// {"whitespace", `\s+`, nil},
	// {"Float", `[-+]?\d*\.\d+`, nil},
	// {"Term", `[{}\[\]=;\n\t\.#]`, nil},
	{"Term", `[\[\]\.]`, nil},
	// {"RangeInt", `\d+(\.\.)?`, nil},
	// {"Punct", `[-,()*/+%{};&!=:<>]|\[|\]`, nil},
	// {"Punct", `[-[!@#$%^&*()+_={}\|:;"'<,>.?/]|]`, nil},
	{"Punct", `[\[\.\]]`, nil},
})

var parser = participle.MustBuild(&Field{},
	participle.Unquote("String"),
	// participle.Lexer(basicLexer),
	// participle.Trace(os.Stdout),
)

const array1 = `
array[]
`

const array2 = `
array[65]
`

const array3 = `
array[5..]
`

const array4 = `
array[1..9]
`

func main() {
	fmt.Println("---------------------- array1 ----------------------")
	fmt.Println(get("array1", array1))
	fmt.Println("---------------------- array2 ----------------------")
	fmt.Println(get("array2", array2))
	fmt.Println("---------------------- array3 ----------------------")
	fmt.Println(get("array3", array3))
	fmt.Println("---------------------- array4 ----------------------")
	fmt.Println(get("array4", array4))
}

func get(name, str string) string {
	p := &Field{}
	if err := parser.ParseString(name, str, p); err != nil {
		str := fmt.Sprintf("%+v\n---\nPartial AST:\n%s", err, spew.Sdump(p))
		panic(str)
	}

	return spew.Sdump(p)
}
```

We've also tried the following statements:
```go
	Min     *int64 `"[" ( ( @Int (?= "##" ) )?`
	IsRange *bool  `      @("##")?`
	Max     *int64 `      @Int? )? "]"`

// =======================

	Min     *int64 `( ( @Int (?= ".." ) )?`
	IsRange *bool  `      @("..")?`
	Max     *int64 `      @Int? )?`
```

(And many other grammar definitions).

All of them will not pass `array3`:
```
---------------------- array1 ----------------------
(*main.Field)(0xc000138640)({
 Pos: (lexer.Position) array1:2:1,
 IsArray: (bool) true,
 Array: (*main.ArrayType)(<nil>)
})

---------------------- array2 ----------------------
(*main.Field)(0xc000138740)({
 Pos: (lexer.Position) array2:2:1,
 IsArray: (bool) true,
 Array: (*main.ArrayType)(0xc000138840)({
  Pos: (lexer.Position) array2:2:7,
  Min: (*int64)(0xc000130748)(65),
  IsRange: (*bool)(<nil>),
  Max: (*int64)(<nil>)
 })
})

---------------------- array3 ----------------------
panic: array3:2:7: unexpected token "5." (expected "]")
---
Partial AST:
(*main.Field)(0xc000138880)({
 Pos: (lexer.Position) array3:2:1,
 IsArray: (bool) true,
 Array: (*main.ArrayType)(<nil>)
})


goroutine 1 [running]:
main.get(0x56d85b, 0x6, 0x56ee67, 0xc, 0x1, 0x35)
        /root/.go/src/__test/participle/array/main.go:81 +0x257
main.main()
        /root/.go/src/__test/participle/array/main.go:72 +0x2d3
exit status 2
```

It also doesn't work if `array3` is declared like this: `array[5 ..]`.
`participle` does not expect the dot character to be there.

**Comment by l0nax** [comment]
Also the following grammar won't work:
```go
type ArrayType struct {
	Pos    lexer.Position

	Min     *int64 `@Number?`
	// IsRange *bool  `              ( @".."`
	Max     *int64 `( ( ".." @Int? ) )?`}

type Field struct {
	Pos    lexer.Position

	IsArray bool       `( @"array" `
	Array   *ArrayType ` "[" @@? "]" )`
}
```

**Comment by alecthomas** [comment]
This is a bug yes, but in your lexer, not in Participle, as can be seen from the error message:

> unexpected token "5."

This indicates that the lexer is returning "5." as a single token rather than two separate tokens. Participle grammars operate on whole tokens only. Similarly if your lexer yields `.` as a single token, the grammar won't be able to match `..` as a single token.

Here's a working version with tests:

```go
package main

import (
	"testing"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
	"github.com/alecthomas/participle/v2/lexer/stateful"
	"github.com/stretchr/testify/require"
)

type ArrayType struct {
	Pos lexer.Position

	Min     *int64 `@Int?`
	IsRange bool   `( @("." ".")? )?`
	Max     *int64 `( @Int? )?`
}

type Field struct {
	Pos lexer.Position

	IsArray bool       `@"array"`
	Array   *ArrayType ` "[" @@? "]"`
}

var basicLexer = stateful.MustSimple([]stateful.Rule{
	{"Int", `\d+`, nil},
	{"Term", `\w+`, nil},
	{"Punct", `[][.]`, nil},
})

var parser = participle.MustBuild(&Field{},
	participle.Lexer(basicLexer),
)

func intp(n int64) *int64 { return &n }

func TestParse(t *testing.T) {
	tests := []struct {
		input    string
		expected *Field
	}{
		{"array[]", &Field{
			Pos:     lexer.Position{Line: 1, Column: 1},
			IsArray: true,
			Array:   nil,
		}},
		{"array[1..]", &Field{
			Pos:     lexer.Position{Line: 1, Column: 1},
			IsArray: true,
			Array: &ArrayType{
				Pos:     lexer.Position{Line: 1, Column: 7, Offset: 6},
				Min:     intp(1),
				IsRange: true,
			},
		}},
		{"array[1..97]", &Field{
			Pos:     lexer.Position{Line: 1, Column: 1},
			IsArray: true,
			Array: &ArrayType{
				Pos:     lexer.Position{Line: 1, Column: 7, Offset: 6},
				Min:     intp(1),
				IsRange: true,
				Max:     intp(97),
			},
		}},
		{"array[..97]", &Field{
			Pos:     lexer.Position{Line: 1, Column: 1},
			IsArray: true,
			Array: &ArrayType{
				Pos:     lexer.Position{Line: 1, Column: 7, Offset: 6},
				IsRange: true,
				Max:     intp(97),
			},
		}},
	}
	for _, test := range tests {
		actual := &Field{}
		err := parser.ParseString("", test.input, actual)
		require.NoError(t, err)
		require.Equal(t, test.expected, actual)
	}
}
```
