### ISSUE TITLE
Expression using double quotes

### ISSUE THREAD

**Issue by bravbravbrav** [alecthomas/participle#417]
I believe that there might be some issue related to double quotes.

# Code:
```go
package main

import (
    "fmt"

    "github.com/alecthomas/participle/v2"
    "github.com/alecthomas/participle/v2/lexer"
)

type Syntax struct {
    Strings []*String `@@*`
}

type String struct {
    Value string `'"' @character '"'`
}

var rules = lexer.MustSimple([]lexer.SimpleRule{
    {`character`, `[^"]`},
})

var parser = participle.MustBuild[Syntax](
    participle.Lexer(rules),
)

func main() {
    fmt.Println(parser.String())
}
```

# Output
```
panic: String:1:1: Strings: invalid syntax: "\"\"\""

goroutine 1 [running]:
github.com/alecthomas/participle/v2.MustBuild[...](...)
	/tmp/gopath1215137364/pkg/mod/github.com/alecthomas/participle/v2@v2.1.1/parser.go:55
main.init()
	/tmp/sandbox1046517504/prog.go:22 +0x112
```

# Expected output
```
Syntax = String* .
String = '"' <character> '"' .
```

**Comment by alecthomas** [comment]
You'll need to use:

```go
    Value string `"\"" @character "\""`
```

This limitation is, IIRC, because of how Participle uses the Go lexer internally.

**Comment by bravbravbrav** [comment]
Cool. I recommend documenting this behavior though. Thank you for your work :)

**Comment by bravbravbrav** [comment]
@alecthomas I tried to use your suggestion in my code sample, but it still results in error:

# Code
```go
package main

import (
	"fmt"
	"os"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
)

type Syntax struct {
	Strings []*String `@@*`
}

type String struct {
	Value string `"\"" @character* "\""`
}

var rules = lexer.MustSimple([]lexer.SimpleRule{
	{`character`, `[^"]`},
})

var parser = participle.MustBuild[Syntax](
	participle.Lexer(rules),
)

func main() {
	syntax, err := parser.ParseString("code", `"a"`)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Printf("%v\n", syntax)
}
```

# Result
```
code:1:1: invalid input text "\"a\""
```
