### ISSUE TITLE
Lexer panics for unterminated single quoted strings

### ISSUE THREAD

**Issue by AndrewC-B** [alecthomas/participle#48]
Here's a working example, which causes a panic for me with the current version of Participle.

```
package main

import (
  "fmt"
  "github.com/alecthomas/participle"
)

type Field struct {
  Name  string `@String`
  Value string `":" @String`
}

type Dict struct {
  Fields []*Field `[ "{" [ @@ { "," @@ } ] "}" ]`
}

func Parse(src string) (out map[string]string, err error) {
  parser, err := participle.Build(&Dict{})
  d := &Dict{}
  err = parser.ParseString(src, d)
  if err != nil {
    return nil, err
  }
  out = make(map[string]string)
  for _, f := range d.Fields {
    out[f.Name] = f.Value
  }
  return out, nil
}

func main() {
  out, err := Parse("{ 'foo")
  if err != nil {
    fmt.Println(err)
      return
    }
  fmt.Println(out)
}
```

```
panic: <source>:1:7: literal not terminated

goroutine 1 [running]:
github.com/alecthomas/participle/lexer.Lex.func1(0xc00009e100, 0x4e5232, 0x16)
	/home/acb/dev/participle/lexer/text_scanner.go:56 +0x19c
text/scanner.(*Scanner).error(0xc00009e100, 0x4e5232, 0x16)
	/usr/lib/golang/src/text/scanner/scanner.go:327 +0x2be
text/scanner.(*Scanner).scanString(0xc00009e100, 0xc000000027, 0x495316)
	/usr/lib/golang/src/text/scanner/scanner.go:476 +0xae
text/scanner.(*Scanner).scanChar(0xc00009e100)
	/usr/lib/golang/src/text/scanner/scanner.go:501 +0x33
text/scanner.(*Scanner).Scan(0xc00009e100, 0x586a9b)
	/usr/lib/golang/src/text/scanner/scanner.go:599 +0x363
github.com/alecthomas/participle/lexer.(*textScannerLexer).Next(0xc00000a780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/acb/dev/participle/lexer/text_scanner.go:89 +0x69
github.com/alecthomas/participle/lexer.(*lookaheadLexer).Next(0xc000080630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/acb/dev/participle/lexer/peek.go:36 +0x161
github.com/alecthomas/participle.newRewinder(0x7fa34edfd048, 0xc000080630, 0x4c8900, 0x4c74a0, 0x595f00)
	/home/acb/dev/participle/context.go:84 +0x89
github.com/alecthomas/participle.newParseContext(0x7fa34edfd048, 0xc000080630, 0x1, 0xc000080660, 0xc000080630, 0x0, 0x0)
	/home/acb/dev/participle/context.go:25 +0x39
github.com/alecthomas/participle.(*Parser).Parse(0xc0000221e0, 0x4fbe00, 0xc00000a760, 0x4b8680, 0xc00000a740, 0xc00000e201, 0xc00000a740)
	/home/acb/dev/participle/parser.go:137 +0x43c
github.com/alecthomas/participle.(*Parser).ParseString(0xc0000221e0, 0x4e292e, 0x6, 0x4b8680, 0xc00000a740, 0xc0000221e0, 0x0)
	/home/acb/dev/participle/parser.go:218 +0x93
main.Parse(0x4e292e, 0x6, 0x404f30, 0xc00007e058, 0x0)
	/home/acb/dev/participle/_examples/bug_mwe/main.go:20 +0xbd
main.main()
	/home/acb/dev/participle/_examples/bug_mwe/main.go:32 +0x3a
exit status 2

```

[This](https://github.com/AndrewC-B/participle/commit/c2c490dcb3091ad82ad1872e2afa5aec0fdd2dd6) seems to fix the issue. Would you accept a pull request?

```
> git checkout lexer-panic
Switched to branch 'lexer-panic'
> go run _examples/bug_mwe/main.go
<source>:1:7: literal not terminated
```

**Comment by alecthomas** [comment]
Definitely! Except please call the field `err` rather than `error`.

**Comment by alecthomas** [comment]
Thanks!
